<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 FINAL//EN">
<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">
<TITLE>Ferramenta de Tradução</TITLE>
<FRAMESET BORDER="1" FRAMESPACING="0" FRAMEBORDER="1" COLS="200,*">
    <FRAME NAME="menu" SRC="menu.php" SCROLLING=NO MARGINWIDTH="2" MARGINHEIGHT="1" FRAMEBORDER=NO BORDER="0" NORESIZE>
    <FRAME NAME="_AREA_" SRC="apresentacao.php" SCROLLING=AUTO MARGINWIDTH=2 MARGINHEIGHT=2>
</FRAMESET>
<noframes></noframes>
</HEAD>
</HTML>